"""
Pydantic Schemas for the AI Module

This file defines the Pydantic models used for data serialization and
documentation in the AI-powered features of the application.
"""

import enum
from pydantic import BaseModel, Field
from typing import List
from datetime import datetime

class InsightSeverity(str, enum.Enum):
    """Enumeration for the severity level of an AI-generated insight."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"

class Insight(BaseModel):
    """Schema for a single AI-generated financial insight."""
    id: str = Field(..., description="A unique identifier for the insight.", example="insight-123")
    title: str = Field(..., description="A short, descriptive title for the insight.", example="Unusual Spending in 'Dining Out'")
    description: str = Field(
        ...,
        description="A detailed explanation of the insight and its implications.",
        example="Your spending on dining out this month is 50% higher than your average."
    )
    severity: InsightSeverity = Field(
        ...,
        description="The severity level of the insight.",
        example=InsightSeverity.MEDIUM
    )
    generated_at: datetime = Field(..., description="The timestamp when the insight was generated.")

class AIInsightsResponse(BaseModel):
    """Schema for the response containing a list of AI-generated insights."""
    insights: List[Insight] = Field(..., description="A list of financial insights generated by the AI.")